#!/usr/bin/env python3
"""Record the indexed APK versions in the generated F-Droid metadata.

fdroidserver only treats a version as "current" if the app metadata names it in
``CurrentVersionCode``, and it only attaches per-version data to versions listed
under ``Builds``. A binary repo like this one has no build recipes, so those
fields are synthesized here from the APKs that were actually collected.

Usage:
    scripts/fdroid/apply-versions.py <fdroid-root> <application-id>
"""

from __future__ import annotations

import sys
from pathlib import Path

from androguard.core.apk import APK
from loguru import logger

# androguard logs one line per parsed AXML chunk at DEBUG, which buries the
# build output.
logger.remove()


def read_versions(repo_dir: Path, app_id: str) -> list[tuple[int, str]]:
    """Parse each collected APK once, rejecting anything that is not this app."""
    versions: dict[int, str] = {}
    for apk_path in sorted(repo_dir.glob("*.apk")):
        apk = APK(str(apk_path))
        package = apk.get_package()
        if package != app_id:
            raise SystemExit(f"{apk_path.name} declares {package}, expected {app_id}")
        code = apk.get_androidversion_code()
        name = apk.get_androidversion_name()
        if code is None:
            print(f"warning: {apk_path.name} has no versionCode", file=sys.stderr)
            continue
        versions[int(code)] = name or ""
    return sorted(versions.items())


def render_block(versions: list[tuple[int, str]]) -> str:
    current_code, current_name = versions[-1]
    lines = [
        "",
        "# Generated by scripts/fdroid/apply-versions.py from the collected APKs.",
        f"CurrentVersion: {current_name}",
        f"CurrentVersionCode: {current_code}",
        "Builds:",
    ]
    for code, name in versions:
        lines.append(f"  - versionName: {name}")
        lines.append(f"    versionCode: {code}")
    return "\n".join(lines) + "\n"


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2

    fdroid_root = Path(sys.argv[1])
    app_id = sys.argv[2]

    repo_dir = fdroid_root / "repo"
    metadata_file = fdroid_root / "metadata" / f"{app_id}.yml"

    if not metadata_file.exists():
        print(f"metadata file not found: {metadata_file}", file=sys.stderr)
        return 1

    versions = read_versions(repo_dir, app_id)
    if not versions:
        print(f"no APKs with a versionCode found in {repo_dir}", file=sys.stderr)
        return 1

    with metadata_file.open("a", encoding="utf-8") as handle:
        handle.write(render_block(versions))

    codes = ", ".join(f"{name} ({code})" for code, name in versions)
    print(f"  recorded versions: {codes}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
